kafka:
  topic: "wikimedia.recentchange"
opensearch:
  index: "wikimedia"
server:
  port: 8051
spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:"127.0.0.1:9092"}
    consumer:
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: consumer-opensearch-demo
      auto-offset-reset: latest
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus