scrape_configs:
  - job_name: 'kafka-producer-wikimedia'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8050']
  - job_name: 'kafka-consumer-opensearch'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8051']
