scrape_configs:
  - job_name: 'kafka-producer-wikimedia'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['kafka-producer-wikimedia:8050']
  - job_name: 'kafka-consumer-opensearch'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['kafka-consumer-opensearch:8051']
